--- AUTOGENERATED FROM gio.norg
local PACK_PATH = vim.fn.stdpath("data") .. "/site/pack"
local function ensure(repository, kind)
    kind = kind or "opt"
    local name = vim.split(repository, "/")[2]
    local destination = string.format(
        "%s/packer/%s/%s", PACK_PATH, kind, name
    )
    if vim.fn.empty(vim.fn.glob(destination)) > 0 then
        vim.notify("GIO: auto-installing " .. repository .. "...")
        vim.fn.system({
            "git", "clone", "--depth", "1",
            "https://github.com/" .. repository, destination,
        })
        if vim.v.shell_error ~= 0 then
            vim.notify(
                "GIO: failed to auto-install " .. repository .. "...",
                vim.log.levels.ERROR
            )
        else
            vim.notify("GIO: auto-installed " .. repository .. "...")
        end
    end
end
local function is_installed(name, kind)
    kind = kind or "opt"
    return vim.fn.empty(vim.fn.glob(string.format("%s/packer/%s/%s", PACK_PATH, kind, name))) == 0
end
vim.defer_fn(function()
    ensure "wbthomason/packer.nvim"
    ensure "rktjmp/hotpot.nvim"

    if is_installed "hotpot.nvim" then
        vim.api.nvim_command "packadd hotpot.nvim"
        require("hotpot").setup {}
    end

    vim.api.nvim_command "packadd packer.nvim"
end, 0)
