--- AUTOGENERATED FROM gio.norg
return {
    utils = require "gio.utils",
    tsinstall = require "gio.utils".tsinstall,
    plug = require "gio.plugin.manager".install,
    load_modules = require "gio.utils".autoload_modules,
    set = require "gio.utils".set,
}