--- AUTOGENERATED FROM gio.norg
local packer = {}
local Manager = {
   plugins = {},
}
function Manager.install()
    local _packer = {}
    local plugins = Manager.plugins
    for plugin_string, spec in pairs(plugins) do
        local module, location = unpack(vim.split(plugin_string, "@"))
        if vim.tbl_isempty(spec) then
            table.insert(_packer, location)
        else
            if type(spec.config) == "string" then
                local _foo, _bar = string.find(spec.config, "@", 1, true)
                if _foo ~= nil then
                    spec.config = [[require("modules.]] .. module .. "." .. spec.config:gsub("@", "") .. [[")]]
                end
            end
            table.insert(_packer, vim.tbl_extend("force", {location}, spec))
        end
    end
    require("packer").startup(function(use)
        for _, specs in pairs(_packer) do
            use(specs)
        end
        use "wbthomason/packer.nvim"
    end)
end
return Manager